### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by darwinsoftware** [FosterCommerce/entry-type-rules#12]
Hello, are you planning to update this plugin to support Craft 5?

**Comment by sjcallender** [comment]
@darwinsoftware - Yes, we are. We'll lock in the specifics soon so it doesn't get forgotten.

**Comment by darwinsoftware** [comment]
@sjcallender that's great news - thank you for confirming!

**Comment by ishetnogferre** [comment]
@sjcallender Great to hear! Any idea on timeframe? We could really use this in an upcoming Craft 5 project 🤩

**Comment by johnnynotsolucky** [comment]
🎉 Craft 5 support has been added in https://github.com/FosterCommerce/entry-type-rules/tree/3.0.0
