### ISSUE TITLE
Craft 4 compatibility 

### ISSUE THREAD

**Issue by twitcher07** [FosterCommerce/entry-type-rules#4]
Hi,

I was looking at maybe using this plugin but realized it's not compatible with Craft 4. Is there any current plans to release a version for Craft 4?

Thanks for your time!

**Comment by sjcallender** [comment]
Hi @twitcher07 - Yes! We are starting on it next week! Thanks for asking.

**Comment by twitcher07** [comment]
@sjcallender Awesome!

**Comment by peteeveleigh** [comment]
Hi @twitcher07 
We just released v2.0.1 of this plugin which brings Craft 4 compatibility.
Sorry for the delay!

**Comment by twitcher07** [comment]
@sjcallender awesome! I appreciate the work.
