### ISSUE TITLE
Type of fostercommerce\entrytyperules\controllers\SettingsController::$allowAnonymous must be array|int|bool (as in class craft\web\Controller)

### ISSUE THREAD

**Issue by deanfields** [FosterCommerce/entry-type-rules#7]
receiving this error when trying to save settings

**Comment by sjcallender** [comment]
What Craft and Entry Type Rules versions are you using? And PHP version?

**Comment by deanfields** [comment]
PHP version | 8.0.13
Entry Type Rules | 2.0.2
Craft edition & version | Craft Pro 4.0.5.1

**Comment by sjcallender** [comment]
Thanks. We'll get you fixed up by mid-week next week. Enjoy your weekend.

**Comment by peteeveleigh** [comment]
@deanfields I've just released a fix for this issue on v2.0.3

**Comment by deanfields** [comment]
Thanks very much
